services:
  - type: web
    name: petshop
    env: node
    buildCommand: npm install && npm run build
    startCommand: node .output/server/index.mjs
    healthCheckPath: /api/categories
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
